"""
Multi-Language Project Generator
Author: Ashraf Siddiqui
GitHub: https://github.com/AshrafMorningstar
"""

import argparse
import os
import shutil
from pathlib import Path

# Base directory of this package
BASE_DIR = Path(__file__).resolve().parent
TEMPLATE_DIR = BASE_DIR / "templates"

# Mapping language identifiers to template folder names
LANG_TEMPLATES = {
    "html": "html_js",
    "js": "html_js",  # same as html
    "python": "python",
    "swift": "swift",
    "ruby": "ruby",
}

AUTHOR_NAME = "Ashraf Siddiqui"
GITHUB_URL = "https://github.com/AshrafMorningstar"


def copy_template(lang: str, destination: Path):
    """Copy the template files for a given language into the destination directory."""
    template_name = LANG_TEMPLATES.get(lang.lower())
    if not template_name:
        raise ValueError(f"Unsupported language: {lang}")
    src = TEMPLATE_DIR / template_name
    if not src.is_dir():
        raise FileNotFoundError(f"Template directory not found: {src}")
    shutil.copytree(src, destination, dirs_exist_ok=True)

    # Create a personalized README in the project root
    readme_path = destination / "README.md"
    readme_content = f"# {lang.capitalize()} Starter Project\n\n" \
        f"Generated by the Multi‑Language Project Generator.\n\n" \
        f"**Author:** {AUTHOR_NAME}\n" \
        f"**GitHub:** {GITHUB_URL}\n"
    readme_path.write_text(readme_content, encoding="utf-8")


def generate_projects(languages, output_dir: Path):
    output_dir.mkdir(parents=True, exist_ok=True)
    for lang in languages:
        project_dir = output_dir / f"{lang}_project"
        print(f"Generating {lang} project at {project_dir}")
        copy_template(lang, project_dir)


def main():
    parser = argparse.ArgumentParser(description="Generate starter projects for multiple languages.")
    parser.add_argument(
        "--languages",
        nargs="+",
        required=True,
        help="List of language identifiers to generate (e.g., html python swift ruby).",
    )
    parser.add_argument(
        "--output",
        default="generated_projects",
        help="Directory where projects will be created (default: ./generated_projects).",
    )
    args = parser.parse_args()
    output_path = Path(args.output).resolve()
    generate_projects(args.languages, output_path)
    print("All projects generated successfully.")

if __name__ == "__main__":
    main()
