/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

[package]
name = "file_manager"
version = "1.0.0"
authors = ["Ashraf Siddiqui <https://github.com/AshrafMorningstar>"]
edition = "2021"

[dependencies]
