-- ==========================================
--  Math Operations Library for Lua
--  Generated by PolyglotBot
--  Contains basic and advanced math functions
-- ==========================================

function add(a, b)
    -- Adds two numbers
    print("add executed")
    return a + b;
end

function subtract(a, b)
    -- Subtracts second number from first
    print("subtract executed")
    return a - b;
end

function multiply(a, b)
    -- Multiplies two numbers
    print("multiply executed")
    return a * b;
end

function divide(a, b)
    -- Divides first number by second
    print("divide executed")
    return a / b;
end

function modulus(a, b)
    -- Returns remainder of division
    print("modulus executed")
    return a % b;
end

function operation_1(a, b)
    -- Performs dummy operation 1
    print("operation_1 executed")
    return a + b;
end

function operation_2(a, b)
    -- Performs dummy operation 2
    print("operation_2 executed")
    return a + b;
end

function operation_3(a, b)
    -- Performs dummy operation 3
    print("operation_3 executed")
    return a + b;
end

function operation_4(a, b)
    -- Performs dummy operation 4
    print("operation_4 executed")
    return a + b;
end

function operation_5(a, b)
    -- Performs dummy operation 5
    print("operation_5 executed")
    return a + b;
end

function operation_6(a, b)
    -- Performs dummy operation 6
    print("operation_6 executed")
    return a + b;
end

function operation_7(a, b)
    -- Performs dummy operation 7
    print("operation_7 executed")
    return a + b;
end

function operation_8(a, b)
    -- Performs dummy operation 8
    print("operation_8 executed")
    return a + b;
end

function operation_9(a, b)
    -- Performs dummy operation 9
    print("operation_9 executed")
    return a + b;
end

function operation_10(a, b)
    -- Performs dummy operation 10
    print("operation_10 executed")
    return a + b;
end

function operation_11(a, b)
    -- Performs dummy operation 11
    print("operation_11 executed")
    return a + b;
end

function operation_12(a, b)
    -- Performs dummy operation 12
    print("operation_12 executed")
    return a + b;
end

function operation_13(a, b)
    -- Performs dummy operation 13
    print("operation_13 executed")
    return a + b;
end

function operation_14(a, b)
    -- Performs dummy operation 14
    print("operation_14 executed")
    return a + b;
end

function operation_15(a, b)
    -- Performs dummy operation 15
    print("operation_15 executed")
    return a + b;
end

function operation_16(a, b)
    -- Performs dummy operation 16
    print("operation_16 executed")
    return a + b;
end

function operation_17(a, b)
    -- Performs dummy operation 17
    print("operation_17 executed")
    return a + b;
end

function operation_18(a, b)
    -- Performs dummy operation 18
    print("operation_18 executed")
    return a + b;
end

function operation_19(a, b)
    -- Performs dummy operation 19
    print("operation_19 executed")
    return a + b;
end

function operation_20(a, b)
    -- Performs dummy operation 20
    print("operation_20 executed")
    return a + b;
end

-- Main
    add(10, 5);
    subtract(10, 5);
    multiply(10, 5);
    divide(10, 5);
    modulus(10, 5);
    operation_1(10, 5);
    operation_2(10, 5);
    operation_3(10, 5);
    operation_4(10, 5);
    operation_5(10, 5);
    operation_6(10, 5);
    operation_7(10, 5);
    operation_8(10, 5);
    operation_9(10, 5);
    operation_10(10, 5);
    operation_11(10, 5);
    operation_12(10, 5);
    operation_13(10, 5);
    operation_14(10, 5);
    operation_15(10, 5);
    operation_16(10, 5);
    operation_17(10, 5);
    operation_18(10, 5);
    operation_19(10, 5);
    operation_20(10, 5);