def main():
    print("Hello, World! This is a starter Python project generated by the Multi‑Language Project Generator.")
    print("Author: Ashraf Siddiqui")
    print("GitHub: https://github.com/AshrafMorningstar")

if __name__ == "__main__":
    main()
