/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

def main():
    print("Hello, World! This is a starter Python project generated by the Multi‑Language Project Generator.")
    print("Author: Ashraf Siddiqui")
    print("GitHub: https://github.com/AshrafMorningstar")

if __name__ == "__main__":
    main()
